<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjNUVCA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjNUVCA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTjNUVCA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTjNUVCA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTjNUVCA\App_KernelDevDebugContainer([
    'container.build_hash' => 'TjNUVCA',
    'container.build_id' => '539b7b4f',
    'container.build_time' => 1594298247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjNUVCA');
