<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY30nvTk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY30nvTk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY30nvTk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY30nvTk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY30nvTk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y30nvTk',
    'container.build_id' => '42db3d12',
    'container.build_time' => 1594297615,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY30nvTk');
